# Site settings
title: The Pages of Ali R. Tariq
email: alirushdan@artariq.com
description: A site with my articles and projects and musings
#baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://artariq.com" # the base hostname & protocol for your site
twitter_username: alirtariq
#github_username:  jekyll
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title

#Default settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      author: Ali R. Tariq
      layout: "post"
      comments: true
  -  
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" # previously `page` in Jekyll 2.2.
    values:
      author: Ali R. Tariq
      layout: "page"